title: Roosevelt Station
headerRight: datetime
columns:
  - background: '#1F1129'
    rows:
      - type: singleRoute
        iconType: circle
        iconColor: "#00C62B"
        routeName: "1"
        title: Southbound
        routeId: "40_100479"
        stopId: "1_990004"
      - type: singleRoute
        iconType: circle
        iconColor: "#00C62B"
        routeName: "1"
        title: Northbound
        routeId: "40_100479"
        stopId: "1_990003"
  - background: '#0000000'
    rows:
      - type: singleStop
        title: Bay 2
        routes:
          - route: "62"
            routeId: "1_100252"
            routeColor: "#0054F8"
            routeHeader: "Downtown"
          - route: "45"
            routeId: "1_100225"
            routeHeader: "Loyal Heights"
            routeColor: "#0054F8"
        stopId: "1_36940"
      - type: singleStop
        title: Bay 3
        routes:
          - route: "62"
            routeId: "1_100252"
            routeColor: "#0054F8"
            routeHeader: "Sand Point"
          - route: "45"
            routeId: "1_100225"
            routeHeader: "U District"
            routeColor: "#0054F8"
        stopId: "1_16430"